export type Server = {
  id: string;
  created_at: number;
  owner_id: string;
  approved_at: number | null;
  discord_id: string;
  approximate_member_count: string;
  nsfw: boolean;
  banned: boolean;
  owner_discord_id: string;
  invite_link: string | null;
  name: string;
  icon: string | null;
  approximate_presence_count: string;
  bumped_at: number;
  language: string | null;
  description: string | null;
  tags: string[];
  public: boolean;
  category: string | null;
  updated_at: number | null;
};
